# Introducción a Python y Notebooks
### Autor: Daniela Garza Saenz
### Curso: Modelos de analitica preventiva

# 1. Bienvenida

¡Hola! Vamos a aprender los fundamentos de Python y Notebooks.

### Ejeución de Código en celda
- Presionando Shift + Enter se logra esto, o dando click en el botón de ejecución.
- Para agregar un comentario en código, conocido como 'inline comment', sólo basta con agregar un símbolo de gato "#" al inicio.

In [22]:
("Hola mundo vamos a aprender de los fundamentos de Phythonm")

'Hola mundo vamos a aprender de los fundamentos de Phythonm'

In [23]:
("Hola mundo vamos a aprender de los fundamentos de Phythonm")

'Hola mundo vamos a aprender de los fundamentos de Phythonm'

# 2. Tipos de datos básicos en Python.
En este punto asignaremos un valor a una variable, cuando utilizamos el signo de igual "=" una vez, se asigna un valor (no significa igualdad), y lo que este del lado izquierdo puede llevar el nombre que el desarrollador del código deseé.

In [24]:
# String (str)

nombre

In [25]:
# Números enteros (int)

In [26]:
# Números flotantes o decimales (float)
altura = 1.65
print("mi estatura es", altura)
print(type(altura))

mi estatura es 1.65
<class 'float'>


In [27]:
# Booleanos (bool), refiere a True/False ó 0/1.
estudiante = True
print("soy estudiante", estudiante)
print(type(estudiante))

soy estudiante True
<class 'bool'>


# 3. Estructuras de Datos básicos.

In [28]:
# Listas
frutas = ["manzana", "banana", "cereza"]
print("lista de frutas", frutas)
print(type(frutas))

lista de frutas ['manzana', 'banana', 'cereza']
<class 'list'>


In [29]:
# Diccionarios (normalmente siguen el formato Key/Value)
persona = {"nombre": "Daniela", "edad": 23, "ciudad": "Monterrey"}
print("información de la persona", persona)
print(type(persona))

información de la persona {'nombre': 'Daniela', 'edad': 23, 'ciudad': 'Monterrey'}
<class 'dict'>


In [30]:
# Otra manera de crear un diccionario
persona2 = dict(nombre="Daniela", edad=23, ciudad="Monterrey")
print("información de persona2", persona2)
print(type(persona2))

información de persona2 {'nombre': 'Daniela', 'edad': 23, 'ciudad': 'Monterrey'}
<class 'dict'>


# 4. Estructuras de control

In [31]:
"""
Condicionales 'if statements'
Los principales signos comparativos son:
Menor que <
Mayor que >
Igual que ==
Menor igual <=
Mayor igual >=
"""

edad = 23
if edad >= 18:
    print("eres mayor de edad")
else:
    print("Eres menor de edad")

eres mayor de edad


In [32]:
# Otras formas de 'validar' información de un objeto con estructura de datos
# Ejemplo de listas.
if "manzana" in frutas:
    print("manzana está en la lista")
else:
    print("manzana no está en la lista")

manzana está en la lista


In [33]:
# Bucles
# Ejemplo de un rango a con una lista hecha a mano.
for i in [0, 1, 2, 3, 4, 5]:
    print(i)

0
1
2
3
4
5


In [34]:
"""
Ejemplo de un bucle utilizando función range()
  Nota: En Python, los índices comienzan en 0 y la función range() excluye el valor final.
  Esto es importante tener en cuenta al trabajar con bucles y acceso a elementos en listas o arrays.
  Python sigue la convención de la notación de intervalos en matemáticas y ciencias de la computación [inicio, fin)
"""
for i in range(6):
    print(i)

0
1
2
3
4
5


In [35]:
# Ejemplo con lista
for fruta in frutas:
    print(fruta)

manzana
banana
cereza


In [36]:
# Ejemplo combinado
# combinaremos una condicional con un bucle y utilizaremos un "format string" y variables.
fruta_favorita = "manzana"
for fruta in frutas:
    if fruta == fruta_favorita:
        print(f"La {fruta} es la fruta favorita de Daniela Garza")
    else:
        print(f"La {fruta} no es la fruta favorita de Daniela Garza")

La manzana es la fruta favorita de Daniela Garza
La banana no es la fruta favorita de Daniela Garza
La cereza no es la fruta favorita de Daniela Garza


# 5. Introducción a Librerías.

### Fundamentos de Programación
1.  **Variable**: Un nombre que se asigna a un valor en un programa. Las
variables pueden almacenar diferentes tipos de datos, como números, texto o estructuras de datos más complejas.
  - `nombre = 'Jorge'`

2.  **Función**: Un bloque de código que realiza una tarea específica y puede ser reutilizado en diferentes partes del programa. Las funciones pueden recibir argumentos y devolver valores.
  - `print()`

3.  **Clase**: Una plantilla para crear objetos que define propiedades y comportamientos. Las clases son fundamentales en la programación orientada a objetos y permiten la creación de objetos personalizados.
  - `str()`, contiene métodos como `.upper()` y `.lower()`
  ```
  nombre = str('Jorge')
  print(nombre.lower())
  ```
  `[out]: 'jorge'`

4.  **Método**: Una función que se define dentro de una clase y se utiliza para realizar operaciones en objetos de esa clase. Los métodos pueden acceder y modificar los atributos de un objeto.
  - `.append()` de la clase `list` que agrega un elemento al final de una lista
    ```
    lista = ['Jorge', 'Ramírez']
    lista.append('García')
    print(lista)
    ```
    `[out]: ['Jorge', 'Ramírez', 'García']`

5.  **Librería** (o biblioteca): Un conjunto de código preescrito que proporciona funcionalidades específicas para ser utilizadas en programas. Las librerías suelen incluir funciones, clases y variables que pueden ser importadas y utilizadas en diferentes proyectos.
  - la librería `math` que proporciona funciones para cálculos matemáticos como `sin()` y `cos()`
  ```
  import math
  result = math.sin(10)
  print(result)
  ```
  `[out]: -0.5440211108893698`

6.  **Paquete**: Un conjunto de librerías o módulos relacionados que se distribuyen juntos. Los paquetes pueden incluir varias librerías, documentación y ejemplos de uso.
  - El paquete `numpy` proporciona herramientas para estructurar y analizar datos.
  ```
  import numpy
  x = np.array([1, 2, 3]) # Creación de un vector.
  suma = np.sum(x)
  print(suma)
  ```
  `[out]: 6`



## 5.1 Numpy

In [37]:
# Empezar a trabajar con Numpy, importar con alias 'np'
import numpy as np

# Crear un vector de una dimensión
vector = np.array([10, 20, 30, 40, 50])
print(vector)
print(type(vector))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [38]:
# Operaciones básicas con el vector
print(vector + 5)
print(vector * 2)
print(np.sqrt(vector))

[15 25 35 45 55]
[ 20  40  60  80 100]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [39]:
# Acceso a elementos
print(vector[2])
print(vector[-2])

30
40


In [40]:
# Uso práctico en negocios: Generar un vector de precios de productos
precios = np.array([299, 399, 499, 599, 699])
print(f"precios originales {precios}")

precios originales [299 399 499 599 699]


In [41]:
# Aplicar un descuento del 10% a todos los productos
precios_descuento = precios * 0.9
print(f"precios con descuento del 10% {precios_descuento}")

precios con descuento del 10% [269.1 359.1 449.1 539.1 629.1]


## 5.2 Pandas

In [42]:
# Se importa con el alias 'pd'
import pandas as pd
# Crear un DataFrame con la información similar a la anterior.
df= pd.DataFrame(
    {"Productos": ["Teclado","Monitor","Celular","Tablet", "Laptop"],
     
     "Precios":[299,399,499,599,699]
        
     }
)
display(df)

# Mostrar el dataframe

,Productos,Precios
0,Teclado,299
1,Monitor,399
2,Celular,499
3,Tablet,599
4,Laptop,699


In [43]:
# Crear el mismo DataFrame a partir de vectores de Numpy